package com.swe645.swe645_Assignment3;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class SurveyController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SurveyRepo surveyRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public ResponseEntity<String> addSurveyData (@RequestBody Surveydata surveydata) {


        Surveydata n = new Surveydata();
        n.setFirstName(surveydata.firstName);
        n.setLastName(surveydata.lastName);
        n.setStreetAddress(surveydata.streetAddress);
        n.setCity(surveydata.city);
        n.setState(surveydata.state);
        n.setZip(surveydata.zip);
        n.setPhoneNumber(surveydata.phoneNumber);
        n.setEmail(surveydata.email);
        n.setDateOfSurvey(surveydata.dateOfSurvey);
        n.setLikedMost(surveydata.likedMost);
        n.setInterestedIn(surveydata.interestedIn);
        n.setLikelihoodOfRecommendation(surveydata.likelihoodOfRecommendation);
        surveyRepository.save(n);
        return ResponseEntity.ok("Data Saved");
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Surveydata> getSurveyData() {

        return surveyRepository.findAll();
    }
}
